/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.44.                      *
*        Compiled Nov 10 2017, 08:52:20                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: PlayerBullet                                          *
* Dimensions:  5 * 5                                                 *
* NumColors:   65536 colors + 8 bit alpha channel                    *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmPlayerBullet;

static GUI_CONST_STORAGE unsigned char _acPlayerBullet[] = {
  0xDD,0xFF,0xFF, 0x3C,0x07,0xE2, 0x04,0x07,0xE2, 0x3C,0x07,0xE2, 0xDD,0xFF,0xFF,
  0x3C,0x07,0xE2, 0x00,0x07,0xE2, 0x00,0x07,0xE2, 0x00,0x07,0xE2, 0x3B,0x07,0xE2,
  0x04,0x07,0xE2, 0x00,0x07,0xE2, 0x00,0x07,0xE2, 0x00,0x07,0xE2, 0x03,0x07,0xE2,
  0x3B,0x07,0xE2, 0x00,0x07,0xE2, 0x00,0x07,0xE2, 0x00,0x07,0xE2, 0x3A,0x07,0xE2,
  0xDB,0xFF,0xFF, 0x3A,0x07,0xE2, 0x03,0x07,0xE2, 0x3A,0x07,0xE2, 0xDB,0xFF,0xFF
};

GUI_CONST_STORAGE GUI_BITMAP bmPlayerBullet = {
  5, // xSize
  5, // ySize
  15, // BytesPerLine
  24, // BitsPerPixel
  (unsigned char *)_acPlayerBullet,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMPAM565
};

/*************************** End of file ****************************/
